import { TDynamicKeys } from '../interfaces';

export const REMOTE_CONFIG_CONSTANTS_SUPPORTED_LANGUAGES =
  'SUPPORTED_LANGUAGES';
export const LOCALIZATION_MAPPING: TDynamicKeys = {
  SW: 'LOCALIZATION_SW',
  EN: 'LOCALIZATION_EN',
  AR: 'LOCALIZATION_AR',
  FR: 'LOCALIZATION_FR',
  PT: 'LOCALIZATION_PT',
  DE: 'LOCALIZATION_DE',
  ES: 'LOCALIZATION_ES',
  RU: 'LOCALIZATION_RU',
};
